data_dir: "/home/duomeitinrfx/data/HistoricalColor-ECCV2012/data/imgs/decade_database/"
encoder: "resnet50"
stage1_ckpt: "results/checkpoints/stage1_resnet50.pt"
mode: "s2.1"
loss: "ce"
exp_name: "E1_resnet50_s2.1"
epochs: 50
batch_size: 32
lr: 0.001
seed: 42
